version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - web_backend
      - web_backend2

  web_backend:
    build: ./services/web_backend
    command: python manage_backend.py run -h 0.0.0.0
    volumes:
      - ./services/web_backend/:/usr/src/backend/
    ports:
      - 4000:4000
    env_file:
      - ./.env.dev
    environment:
      - BACKEND_PORT=4000
    depends_on:
      - db
 
  web_backend2:
    build: ./services/web_backend
    command: python manage_backend.py run -h 0.0.0.0
    volumes:
      - ./services/web_backend/:/usr/src/backend/
    ports:
      - 4001:4001
    env_file:
      - ./.env.dev
    environment:
      - BACKEND_PORT=4001
    depends_on:
      - db
 
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    environment:
      - POSTGRES_USER=test_app
      - POSTGRES_PASSWORD=test_app
      - POSTGRES_DB=counters

volumes:
  postgres_data:
